name: React CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

env:
  NODE_VERSION: "18"

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install dependencies
      - name: Install Dependencies
        working-directory: ./vida-cortex
        run: npm ci

      # Build React app
      - name: Build App
        working-directory: ./vida-cortex
        run: npm run build

      # Upload dist folder as artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: vida-cortex/dist

  #  SAST Job 
  sast:
    name: Security Scan (SAST)
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Semgrep
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"

      # Gitleaks
      - name: Run Gitleaks
        run: |
          docker run --rm -v ${{ github.workspace }}:/path \
          zricethezav/gitleaks:latest detect \
          --source="/path" \
          --verbose \
          --redact

      # Trivy
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

  deploy:
    name: Deploy to Azure Storage Static Website
    runs-on: ubuntu-latest

    # Bypass SAST and deploy after build
    needs: [build]

    steps:
      # Download artifact from build job
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app
          path: dist

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Upload to Azure Storage Static Website
      - name: Deploy to Azure Storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
              --destination '$web' \
              --source dist \
              --auth-mode login \
              --overwrite
